<?php

namespace diagnosticsphp\core\scriptClass;

use diagnosticsphp\core\generalInfoClass\GeneralInfoClass;
use PHPUnit\Framework\TestCase;

class GeneralInfoClassTest extends TestCase
{
    public function expectError(): void
    {
        parent::expectError(); // TODO: Change the autogenerated stub
    }
}
