<?php

namespace diagnosticsphp\core\generalInterface;

use generalInterfaceTest;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * Class generalInterfaceTestSuite
 * @package diagnosticsphp\core\generalInterface
 */
class generalInterfaceTestSuite extends TestCase
{

    /**
     * @covers \PHPUnit\Util\Exception
     */
    public function testDefinition(){
        if ((!file_exists(GENERAL_INTERFACE)) && (!is_readable(GENERAL_INTERFACE))){
            throw new Exception(NON_EXISTENT_OR_NOT_READABLE);
        } else {
            $this->doDelete();
        }
    }

    /**
     * @param string $originalClassName
     * @param array $configuration
     * @return MockObject
     */
    protected function createConfiguredMock(string $originalClassName, array $configuration): MockObject
    {
        return parent::createConfiguredMock($originalClassName, $configuration); // TODO: Change the autogenerated stub
    }

    /**
     * @return void
     */
    public function expectError(): void
    {
        parent::expectError(); // TODO: Change the autogenerated stub
    }
}
